% an interactive Matlab GUI for manually labeling anomalous points with data cursors as ground truth
% output: a binary file indicating anomalous data points

function LoadGUI(outFP,indata,startingCol)
f = figure('units','normalized','outerposition',[0 0 1 1],'Tag','Fig');
ax = axes('Parent',f,'position',[0.13 0.39  0.77 0.54]);
[time_len,colNums] = size(indata);
GUI_IO = struct('raw_data',indata,'output_path',outFP,'total_len',time_len);
hObject = findobj('Tag','Fig');
guidata(hObject,GUI_IO);

% radio button for choosing if the chosen anomalous points are single input points
r_single_pt_control = uicontrol('Parent',f,'Style','radiobutton',...
                  'Tag','r_single_pt_control',...
                  'String','Single Point',...
                  'Position',[281,95,80,30],...
                  'HandleVisibility','on');

% generate a binary code block for recently labeled points
output_btn = uicontrol('Parent',f,'Style','pushbutton','Position',[81,95,80,30],...
           'String','OUTPUT','Callback',@WriteBinary);

% add more anomalous ranges/points into the GUI table
add_btn = uicontrol('Parent',f,'Style','pushbutton','Position',[181,95,80,30],...
           'String','ADD','Callback',@Label);

% clear the GUI table
clear_btn = uicontrol('Parent',f,'Style','pushbutton','Position',[81,125,80,30],...
           'String','CLEAR','Callback',@ClearTable);

% turn to next column
next_btn = uicontrol('Parent',f,'Style','pushbutton','Position',[181,125,80,30],...
           'String','NEXT','Callback',@NextCol);
       
% column No. under labeling
cols = uicontrol(f,'Style','text',...
                'String','Column No.:',...
                'Position',[81 175 80 30]);
col_no = uicontrol(f,'Style','text',...
                'Tag','Col_No',...
                'String',num2str(startingCol),...
                'Position',[181 175 80 30],...
                'HandleVisibility','on');

% total number of columns in the dataset
total = uicontrol(f,'Style','text',...
                'String','# columns in total:',...
                'Position',[81 155 80 30]);

total_no = uicontrol(f,'Style','text',...
                'Tag','Total_Num',...
                'String', colNums,...
                'Position',[181 155 80 30],...
                'HandleVisibility','on');


% Make a table showing all the segments selected
tble = uitable('Parent',f,'Position',[450 88 300 120],'ColumnName',{'start','end'},...
    'Tag','data_holder');

end
